### ISSUE TITLE
'No tracks found!' when searching for 'USA'

### ISSUE THREAD

**Issue by zinosama** [sally/mapjamz#39]
Hey I stumbled upon this project and really really liked the interface and the idea behind it. However, many countries that I tried to search returned empty results. I've tried phrases like 'Korea', 'South Korea', and 'USA', and they're all empty.

**Comment by sally** [comment]
Hi Zino, thanks for commenting! I'm glad you liked the project.

I'm aware that the queries need to be slightly tailored to how the LastFM API accepts country names. According to the [docs](http://www.last.fm/api/show/geo.getTopTracks), countries must be entered in ISO 3166-1 country names standard.

For USA, I found I needed to type "United States", and for South Korea, "Korea, Republic of."

There are some countries that I'd like to sanitize the input for, including some you mentioned: USA, South Korea, Vietnam, Britain ... I'll definitely implement this in the near future when I get time. (ETA 3-4 days?)
